version: "3.9"

services:
  webdav:
    image: nginx:alpine
    container_name: webdav
    volumes:
      - ./data:/var/www/data
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
